export const paths = {
  login: "/login",
  dashboard: "/dashboard",
  effective: "/effective",
  k9: "/k9",
  k9New: "/k9/new",
  humans: "/humans",
  humanNew: "/humans/new",
  humanCertifications: "/humans/certifications",
  humanMovements: "/humans/movements",
  binomials: "/binomials",
  vehicles: "/vehicles",
  occurrences: "/occurrences",
  training: "/training",
  trainingDog: "/training/dogs",
  trainingSession: "/training/sessions",
  trainingEvaluation: "/training/evaluations",
  trainingMatrices: "/training/matrices",
  trainingPromotions: "/training/promotions",
  trainingCurriculums: "/training/curriculums",
  trainingMatrix: "/training-matrix",
  health: "/health",
  healthNutrition: "/health/nutrition",
  inventory: "/inventory",
  reports: "/reports",
  access: "/access",
  shifts: "/shifts",
  me: "/me",
  notifications: "/notifications",
  admin: "/admin",
} as const;

export type AppPath = (typeof paths)[keyof typeof paths];
